### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by avasilic** [yxx4c/prisma-redis-cache#1]
Hi there,

This looks like a really nice and useful project however I had a few questions before using it:

1. Do you have any plans to have an option where queries are cached by default? For my use case it would be a lot easier to just enable caching for everything and then just pass in `cache: false` when I don't want the cache?
2. Have you considered merging https://github.com/yxx4c/prisma-redis-uncache into this package and offering cache invalidation automatically on `.update`, `.updateMany`, and other similar updating queries?

I guess the reason I'm asking these questions is because I enjoyed using https://www.npmjs.com/package/prisma-redis-middleware before it got archived on GitHub, with the automatic invalidation handling and `excludeModels` option.

Thanks

**Comment by yxx4c** [comment]
Hey @net-tech ,

Thanks for showing interest in the extension.

I developed this extension to tackle a specific problem I had, but I'm open to making it useful for more situations.

1. I haven't thought about enabling the cache by default, but I'll explore the possibility of configuring it while extending Prisma.

2. I considered merging everything and creating a new extension with all the cache-uncache features, and helper functions from cache-utils. It might be doable to incorporate this into the configuration, but I want to ensure it's user-friendly. Currently, only read operations are allowed in the cache extension, while modifications are permitted in the uncache extension, hope this makes sense.

If I can devise a logical setup for these options, I'll definitely include them. Thanks! :)

**Comment by avasilic** [comment]
Thanks for your quick response and looking forward to any potential changes!
