### ISSUE TITLE
Question - Which type do I use?

### ISSUE THREAD

**Issue by francopan-contractlabs** [yxx4c/prisma-redis-cache#2]
I am using typescript. 
It seems it is not of type PrismaClient, but something else. Could you provide a type so we can reference it?

**Comment by yxx4c** [comment]
@francopan-contractlabs 

Please use [@yxx4c/prisma-redis-extension](https://github.com/yxx4c/prisma-redis-extension). If you encounter any issues, please open a new issue [here](https://github.com/yxx4c/prisma-redis-extension/issues/new/choose).
